---
- name: Update the packagesand clear cache in Ubuntu
  hosts: localhost
  become: true
  gather_facts: yes
  tasks:
    - name: Update packages
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Cleanup cache and unused packages
      apt:
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

      