---
- hosts: localhost
  become: true
  tasks:
    - name: Install some packages on Ubuntu
      apt:
        name: '{{item}}'
        state: latest
      with_items:
       - nano
       - vim
       - zip
       - unzip
       - git
       - bzip2
      when: ansible_os_family == "Debian"