---
- name: "Hello everyone, this is one play with 2 tasks"
  hosts: localhost
  tasks:
  - name: Creating an empty file
    file:
      path: "/home/ubuntu/file.txt"
      state: touch
      
  - name: Deleting an empty file
    file: path=/home/ubuntu/file.txt state=touch