- name: Copy Module
  hosts: all
  vars:
    fruit: "apple"
    output: "output.txt"
  tasks:
    - name: Copying content to destination file
      copy: 
        content: "{{ fruit }}"
        dest: "{{ output }}"

    - name: "Read a file content"
    shell: |
      cat output.txt
    register: file_content

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"