- name: Jinga2 Template
  hosts: all
  vars:
    fruit: "Updated!!! as Jack Fruit**"
    output: "output.txt"
  tasks:
    - name: Updating the value of Var Fruit via Jinga2
      template: 
        src: "jinga2.j2"
        dest: "{{ output }}"
        
     - name: "Read a file content"
      shell: |
        cat output.txt
      register: file_content

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"