---
- name: lineinfile module demo
  hosts: all
  become: true
  tasks:
    - name: allow password authentication
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        # try without regexp first
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"