---
- name: git module demo
  hosts: all
  vars:
    repo: "git@github.com:Harsha0111/Ansible.git"
    dest: "/home/ubuntu/ssh"
    sshkey: "~/.ssh/id_rsa"
  tasks:
    - name: ensure git pkg installed
      yum:
        name: git
        state: present
        update_cache: true
      become: true

    - name: checkout git repo
        git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"
        key_file: "{{ sshkey }}"
