---
- name: git module demo
  hosts: all
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
      become: true

    - name: checkout git repo
      ansible.builtin.git:
        repo: https://github.com/Harsha0111/Ansible.git
        dest: /home/ubuntu/https