---
- name: git module demo
  hosts: localhost
  tasks:
    - name: ensure git pkg installed
      apt:
        name: git
        state: present
      become: true

    - name: checkout git repo via https
      git:
        repo: https://github.com/Harsha0111/Ansible.git
        dest: /home/ubuntu/https