---
- name: fetch module demo
  hosts: all
  become: true
  vars:
    file: "fetch.txt"
    dump_dir: "download"
  tasks:
    - name: fetch remote file to ansible master
      fetch:
        src: "{{ file }}"
        dest: "{{ dump_dir }}"